go:
    version: 1.14
repository:
    path: github.com/nbarrientos/cryptowat_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - README.md
crossbuild:
    platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm
        - windows/amd64
        - darwin/amd64
